export const actionTypes = {
    // Authentication Actions
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT: 'LOGOUT',
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',
  
    // Player Profile Actions
    FETCH_PLAYER_PROFILE_REQUEST: 'FETCH_PLAYER_PROFILE_REQUEST',
    FETCH_PLAYER_PROFILE_SUCCESS: 'FETCH_PLAYER_PROFILE_SUCCESS',
    FETCH_PLAYER_PROFILE_FAILURE: 'FETCH_PLAYER_PROFILE_FAILURE',
    UPDATE_PLAYER_PROFILE: 'UPDATE_PLAYER_PROFILE',
    UPLOAD_PLAYER_VIDEO: 'UPLOAD_PLAYER_VIDEO',
  
    // Agent Actions
    FETCH_AGENT_PROFILE_REQUEST: 'FETCH_AGENT_PROFILE_REQUEST',
    FETCH_AGENT_PROFILE_SUCCESS: 'FETCH_AGENT_PROFILE_SUCCESS',
    FETCH_AGENT_PROFILE_FAILURE: 'FETCH_AGENT_PROFILE_FAILURE',
    CONTACT_PLAYER_REQUEST: 'CONTACT_PLAYER_REQUEST',
    CONTACT_PLAYER_SUCCESS: 'CONTACT_PLAYER_SUCCESS',
    CONTACT_PLAYER_FAILURE: 'CONTACT_PLAYER_FAILURE',
    SEARCH_PLAYERS: 'SEARCH_PLAYERS',
  
    // Team Actions
    FETCH_TEAM_REQUEST: 'FETCH_TEAM_REQUEST',
    FETCH_TEAM_SUCCESS: 'FETCH_TEAM_SUCCESS',
    FETCH_TEAM_FAILURE: 'FETCH_TEAM_FAILURE',
    UPDATE_TEAM_PROFILE: 'UPDATE_TEAM_PROFILE',
  
    // Chat and Messaging
    SEND_MESSAGE_REQUEST: 'SEND_MESSAGE_REQUEST',
    SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
    SEND_MESSAGE_FAILURE: 'SEND_MESSAGE_FAILURE',
    RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',
  
    // Rankings and Statistics
    FETCH_RANKINGS_REQUEST: 'FETCH_RANKINGS_REQUEST',
    FETCH_RANKINGS_SUCCESS: 'FETCH_RANKINGS_SUCCESS',
    FETCH_RANKINGS_FAILURE: 'FETCH_RANKINGS_FAILURE',
  
    // UI Actions
    TOGGLE_DARK_MODE: 'TOGGLE_DARK_MODE',
    SET_LANGUAGE: 'SET_LANGUAGE',
  
    // Notifications
    FETCH_NOTIFICATIONS_REQUEST: 'FETCH_NOTIFICATIONS_REQUEST',
    FETCH_NOTIFICATIONS_SUCCESS: 'FETCH_NOTIFICATIONS_SUCCESS',
    FETCH_NOTIFICATIONS_FAILURE: 'FETCH_NOTIFICATIONS_FAILURE',
    MARK_NOTIFICATION_READ: 'MARK_NOTIFICATION_READ',
  
    // Miscellaneous Actions
    LOAD_INITIAL_SETTINGS: 'LOAD_INITIAL_SETTINGS',
    UPDATE_APP_CONFIG: 'UPDATE_APP_CONFIG',
    SUBMIT_FEEDBACK_REQUEST: 'SUBMIT_FEEDBACK_REQUEST',
    SUBMIT_FEEDBACK_SUCCESS: 'SUBMIT_FEEDBACK_SUCCESS',
    SUBMIT_FEEDBACK_FAILURE: 'SUBMIT_FEEDBACK_FAILURE',
  
    // Additional action types as required by your app's functionality
  };
  