export const actionTypes = {
    // Authentication Actions
    LOGIN_REQUEST: 'LOGIN_REQUEST' as const,
    LOGIN_SUCCESS: 'LOGIN_SUCCESS' as const,
    LOGIN_FAILURE: 'LOGIN_FAILURE' as const,
    LOGOUT: 'LOGOUT' as const,
    REGISTER_REQUEST: 'REGISTER_REQUEST' as const,
    REGISTER_SUCCESS: 'REGISTER_SUCCESS' as const,
    REGISTER_FAILURE: 'REGISTER_FAILURE' as const,
  
    // Player Profile Actions
    FETCH_PLAYER_PROFILE_REQUEST: 'FETCH_PLAYER_PROFILE_REQUEST' as const,
    FETCH_PLAYER_PROFILE_SUCCESS: 'FETCH_PLAYER_PROFILE_SUCCESS' as const,
    FETCH_PLAYER_PROFILE_FAILURE: 'FETCH_PLAYER_PROFILE_FAILURE' as const,
    UPDATE_PLAYER_PROFILE: 'UPDATE_PLAYER_PROFILE' as const,
    UPLOAD_PLAYER_VIDEO: 'UPLOAD_PLAYER_VIDEO' as const,
  
    // Agent Actions
    FETCH_AGENT_PROFILE_REQUEST: 'FETCH_AGENT_PROFILE_REQUEST' as const,
    FETCH_AGENT_PROFILE_SUCCESS: 'FETCH_AGENT_PROFILE_SUCCESS' as const,
    FETCH_AGENT_PROFILE_FAILURE: 'FETCH_AGENT_PROFILE_FAILURE' as const,
    CONTACT_PLAYER_REQUEST: 'CONTACT_PLAYER_REQUEST' as const,
    CONTACT_PLAYER_SUCCESS: 'CONTACT_PLAYER_SUCCESS' as const,
    CONTACT_PLAYER_FAILURE: 'CONTACT_PLAYER_FAILURE' as const,
    SEARCH_PLAYERS: 'SEARCH_PLAYERS' as const,
  
    // Team Actions
    FETCH_TEAM_REQUEST: 'FETCH_TEAM_REQUEST' as const,
    FETCH_TEAM_SUCCESS: 'FETCH_TEAM_SUCCESS' as const,
    FETCH_TEAM_FAILURE: 'FETCH_TEAM_FAILURE' as const,
    UPDATE_TEAM_PROFILE: 'UPDATE_TEAM_PROFILE' as const,
  
    // Chat and Messaging
    SEND_MESSAGE_REQUEST: 'SEND_MESSAGE_REQUEST' as const,
    SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS' as const,
    SEND_MESSAGE_FAILURE: 'SEND_MESSAGE_FAILURE' as const,
    RECEIVE_MESSAGE: 'RECEIVE_MESSAGE' as const,
  
    // Rankings and Statistics
    FETCH_RANKINGS_REQUEST: 'FETCH_RANKINGS_REQUEST' as const,
    FETCH_RANKINGS_SUCCESS: 'FETCH_RANKINGS_SUCCESS' as const,
    FETCH_RANKINGS_FAILURE: 'FETCH_RANKINGS_FAILURE' as const,
  
    // UI Actions
    TOGGLE_DARK_MODE: 'TOGGLE_DARK_MODE' as const,
    SET_LANGUAGE: 'SET_LANGUAGE' as const,
  
    // Notifications
    FETCH_NOTIFICATIONS_REQUEST: 'FETCH_NOTIFICATIONS_REQUEST' as const,
    FETCH_NOTIFICATIONS_SUCCESS: 'FETCH_NOTIFICATIONS_SUCCESS' as const,
    FETCH_NOTIFICATIONS_FAILURE: 'FETCH_NOTIFICATIONS_FAILURE' as const,
    MARK_NOTIFICATION_READ: 'MARK_NOTIFICATION_READ' as const,
  
    // Miscellaneous Actions
    LOAD_INITIAL_SETTINGS: 'LOAD_INITIAL_SETTINGS' as const,
    UPDATE_APP_CONFIG: 'UPDATE_APP_CONFIG' as const,
    SUBMIT_FEEDBACK_REQUEST: 'SUBMIT_FEEDBACK_REQUEST' as const,
    SUBMIT_FEEDBACK_SUCCESS: 'SUBMIT_FEEDBACK_SUCCESS'as const ,
    SUBMIT_FEEDBACK_FAILURE: 'SUBMIT_FEEDBACK_FAILURE' as const,
  
  } as const;
  